services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment: 
      LISTEN_PORT: 8080
      OSRM_HOST: 'osrm'
      STEAM_API_KEY: ${STEAM_API_KEY}
  osrm:
    build:
      context: ./osrm
